@extends('layouts.layout')

@section('title', 'Dashboard - DailyMood')

@section('content')
<div style="display: grid; grid-template-columns: 1fr 300px; gap: 1.5rem; align-items: start;">
    
    <!-- Left Column: Calendar -->
    <div class="card" style="margin-bottom: 0;">
        <div class="calendar-header">
            <h2 style="font-size: 1.25rem; margin: 0; color: var(--text-heading);">Kalender Mood</h2>
            <div style="display: flex; gap: 0.5rem; align-items: center;">
                <button class="calendar-nav-btn" onclick="changeMonth(-1)" style="width: 32px; height: 32px; font-size: 0.875rem;">←</button>
                <div class="calendar-month" id="calendarMonth" style="font-size: 1rem; min-width: 140px; text-align: center;"></div>
                <button class="calendar-nav-btn" onclick="changeMonth(1)" style="width: 32px; height: 32px; font-size: 0.875rem;">→</button>
            </div>
        </div>
        
        <div class="calendar-grid" id="calendarGrid" style="gap: 1px; background: var(--border-color); border: 1px solid var(--border-color); overflow: hidden; border-radius: var(--radius);">
            <!-- Calendar generated by JS -->
        </div>
        
        <div style="margin-top: 1rem; display: flex; gap: 1rem; font-size: 0.75rem; color: var(--text-muted); justify-content: center;">
            <div style="display: flex; align-items: center; gap: 0.25rem;">
                <span style="width: 8px; height: 8px; background: var(--success); border-radius: 50%;"></span> Mood
            </div>
            <div style="display: flex; align-items: center; gap: 0.25rem;">
                <span style="width: 8px; height: 8px; background: var(--bg-body); border: 1px solid var(--border-color); border-radius: 50%;"></span> Kosong
            </div>
        </div>
    </div>

    <!-- Right Column: Quick Actions & Summary -->
    <div style="display: flex; flex-direction: column; gap: 1.5rem;">
        <!-- Quick Action Widget -->
        <div class="card" style="text-align: center; margin-bottom: 0;">
            <div style="width: 48px; height: 48px; background: var(--primary-bg); color: var(--primary); border-radius: 50%; display: flex; align-items: center; justify-content: center; margin: 0 auto 1rem auto; font-size: 1.5rem;">✨</div>
            <h3 style="font-size: 1.125rem; margin-bottom: 0.5rem;">Apa kabar hari ini?</h3>
            <p style="color: var(--text-body); font-size: 0.875rem; margin-bottom: 1.5rem;">Luangkan waktu sejenak untuk mencatat perasaan Anda.</p>
            <a href="{{ route('daily-moods.create') }}" class="btn btn-primary" style="width: 100%;">
                Catat Mood Sekarang
            </a>
        </div>
        
        <!-- Mini Stats Widget (Optional/Placeholder) -->
        <div class="card" style="margin-bottom: 0; padding: 1.5rem;">
            <h4 style="font-size: 0.875rem; color: var(--text-muted); text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 1rem;">Statistik Bulan Ini</h4>
            <div style="display: flex; justify-content: space-between; align-items: center;">
                <div>
                    <span style="display: block; font-size: 1.5rem; font-weight: 700; color: var(--text-heading);">{{ $dailyMoods->where('created_at', '>=', now()->startOfMonth())->count() ?? 0 }}</span>
                    <span style="font-size: 0.75rem; color: var(--text-muted);">Catatan Mood</span>
                </div>
                 <!-- Simple placeholder chart/icon -->
                 <div style="width: 40px; height: 40px; border-radius: 50%; background: #f1f5f9; display: flex; align-items: center; justify-content: center; color: #64748b;">📊</div>
            </div>
        </div>
    </div>

</div>

<!-- Modal -->
<div id="moodHistoryModal" class="mood-modal">
    <div class="mood-modal-content" style="max-width: 450px;">
        <button onclick="closeMoodHistory()" class="mood-modal-close" style="top: 1rem; right: 1rem; background: transparent; color: var(--text-muted); font-size: 1.5rem;">&times;</button>
        <h3 id="modalDate" style="margin-bottom: 1.5rem; color: var(--text-heading); font-size: 1.125rem; padding-bottom: 1rem; border-bottom: 1px solid var(--border-color);"></h3>
        <div id="modalContent"></div>
    </div>
</div>

<style>
    /* Dashboard specific overrides */
    @media (max-width: 768px) {
        div[style*="grid-template-columns"] {
            grid-template-columns: 1fr !important;
        }
    }

    .calendar-container {
        /* Reset container styles for this layout */
        background: transparent;
        box-shadow: none;
        backdrop-filter: none;
        border: none;
        padding: 0;
        margin: 0;
    }

    .calendar-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 1.5rem;
    }

    .calendar-nav-btn {
        background: var(--bg-body);
        color: var(--text-heading);
        border: 1px solid var(--border-color);
        border-radius: var(--radius);
        cursor: pointer;
        transition: all 0.2s;
        display: flex;
        align-items: center;
        justify-content: center;
        box-shadow: var(--shadow-sm);
    }
    
    .calendar-nav-btn:hover {
        background: #f1f5f9; /* Slate-100 */
        border-color: #cbd5e1;
    }

    /* Grid Modernization */
    .calendar-grid {
        display: grid;
        grid-template-columns: repeat(7, 1fr);
        background-color: var(--border-color);
        gap: 1px;
    }

    .calendar-day-header {
        background: #f8fafc; /* Slate-50 */
        color: var(--text-muted);
        font-size: 0.75rem;
        font-weight: 600;
        text-transform: uppercase;
        padding: 0.75rem 0.5rem;
        text-align: center;
    }

    .calendar-day {
        background: #ffffff;
        min-height: 80px; /* Taller cells */
        padding: 0.5rem;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
        align-items: flex-start; /* Align date to top-left */
        cursor: pointer;
        transition: background 0.2s;
        position: relative;
    }

    .calendar-day:hover {
        background-color: #f8fafc;
    }
    
    .calendar-day-num {
        font-size: 0.875rem;
        font-weight: 500;
        color: var(--text-body);
        margin-bottom: 0.25rem;
    }

    .calendar-day.other-month {
        background-color: #fcfcfc;
        color: #cbd5e1; /* Slate-300 */
    }

    .calendar-day.today {
        background-color: #f0f9ff; /* Sky-50 */
    }
    
    .calendar-day.today .calendar-day-num {
        color: var(--primary);
        font-weight: 700;
    }

    /* Modern Mood Indicator (Dot) */
    .calendar-day.has-mood {
        /* No background change, just the dot/icon */
    }

    .calendar-mood-icon {
        width: 24px;
        height: 24px;
        object-fit: cover;
        border-radius: 50%;
        align-self: center; /* Center icon in cell */
        margin-top: auto;
        margin-bottom: auto;
        border: 1px solid var(--border-color);
    }
    
    .calendar-mood-emoji {
        font-size: 1.25rem;
        align-self: center;
        margin-top: auto;
        margin-bottom: auto;
    }

</style>
@endsection

@section('scripts')
<script>
    const moodDates = @json($moodDates);
    const moodsByDate = @json($moodsByDate);
    let currentMonth = {{ $currentMonth }};
    let currentYear = {{ $currentYear }};

    function generateCalendar() {
        const firstDay = new Date(currentYear, currentMonth - 1, 1);
        const lastDay = new Date(currentYear, currentMonth, 0);
        const daysInMonth = lastDay.getDate();
        const startingDayOfWeek = firstDay.getDay();
        
        const dayNames = ['Min', 'Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab'];
        const monthNames = [
            'Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni',
            'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember'
        ];

        document.getElementById('calendarMonth').textContent = 
            monthNames[currentMonth - 1] + ' ' + currentYear;

        let calendarHTML = '';
        
        // Day headers
        dayNames.forEach(day => {
            calendarHTML += `<div class="calendar-day-header">${day}</div>`;
        });

        // Empty cells for days before month starts
        for (let i = 0; i < startingDayOfWeek; i++) {
            calendarHTML += `<div class="calendar-day other-month"></div>`;
        }

        // Days of the month
        const today = new Date();
        today.setHours(0, 0, 0, 0);
        
        for (let day = 1; day <= daysInMonth; day++) {
            const dateStr = `${currentYear}-${String(currentMonth).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
            const dateObj = new Date(currentYear, currentMonth - 1, day);
            dateObj.setHours(0, 0, 0, 0);
            
            const isToday = dateObj.getTime() === today.getTime();
            const hasMood = moodDates.includes(dateStr);
            
            let classes = 'calendar-day';
            if (isToday) classes += ' today';
            if (hasMood) classes += ' has-mood';
            
            // Get mood icon for this date
            let moodIcon = '';
            if (hasMood && moodsByDate[dateStr] && moodsByDate[dateStr].length > 0) {
                const firstMood = moodsByDate[dateStr][0];
                if (firstMood.mood_image) {
                    moodIcon = `<img src="/${firstMood.mood_image}" alt="" class="calendar-mood-icon">`;
                } else if (firstMood.mood_emoji) {
                    moodIcon = `<span class="calendar-mood-emoji">${firstMood.mood_emoji}</span>`;
                }
            }
            
            if (hasMood) {
                calendarHTML += `<div class="${classes}" onclick="showMoodHistory('${dateStr}')" style="cursor: pointer;" title="Klik untuk melihat mood"><span class="calendar-day-num">${day}</span>${moodIcon}</div>`;
            } else if (isToday) {
                calendarHTML += `<div class="${classes}" onclick="window.location.href='{{ route('daily-moods.create') }}'" style="cursor: pointer;" title="Tambah mood hari ini">${day}</div>`;
            } else {
                calendarHTML += `<div class="${classes}">${day}</div>`;
            }
        }

        document.getElementById('calendarGrid').innerHTML = calendarHTML;
    }

    function showMoodHistory(dateStr) {
        const moods = moodsByDate[dateStr];
        if (!moods || moods.length === 0) {
            return;
        }

        const date = new Date(dateStr);
        const options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };
        document.getElementById('modalDate').textContent = '📅 ' + date.toLocaleDateString('id-ID', options);

        let contentHTML = '';
        moods.forEach(mood => {
            const moodImage = mood.mood_image ? `<img src="/${mood.mood_image}" alt="${mood.mood_name}" style="width: 60px; height: 60px; object-fit: contain; border-radius: 12px; box-shadow: 0 2px 8px rgba(0,0,0,0.1);">` : `<span style="font-size: 40px;">${mood.mood_emoji}</span>`;
            
            contentHTML += `
                <div style="background: #f8f9fa; border-left: 4px solid #11a8d2; padding: 20px; border-radius: 16px; margin-bottom: 15px;">
                    <div style="display: flex; align-items: center; gap: 15px; margin-bottom: 12px;">
                        ${moodImage}
                        <div>
                            <h4 style="margin: 0; color: #1a1a2e; font-size: 18px; font-weight: 700;">${mood.mood_name}</h4>
                            <p style="margin: 5px 0 0 0; color: #666; font-size: 14px;">📅 ${mood.mood_date}</p>
                        </div>
                    </div>
                    <p style="margin: 12px 0 0 0; color: #495057; line-height: 1.7; font-size: 14px;"><strong style="color: #11a8d2;">Alasan:</strong> ${mood.reason}</p>
                    <div style="margin-top: 15px;">
                        <a href="/daily-moods/${mood.id}" class="btn btn-primary" style="text-decoration: none; padding: 10px 20px; font-size: 14px; display: inline-block;">👁️ Lihat Detail</a>
                    </div>
                </div>
            `;
        });

        document.getElementById('modalContent').innerHTML = contentHTML;
        document.getElementById('moodHistoryModal').style.display = 'flex';
    }

    function closeMoodHistory() {
        document.getElementById('moodHistoryModal').style.display = 'none';
    }

    function changeMonth(delta) {
        currentMonth += delta;
        if (currentMonth > 12) {
            currentMonth = 1;
            currentYear++;
        } else if (currentMonth < 1) {
            currentMonth = 12;
            currentYear--;
        }
        generateCalendar();
    }

    // Close modal when clicking outside
    document.getElementById('moodHistoryModal').addEventListener('click', function(e) {
        if (e.target === this) {
            closeMoodHistory();
        }
    });

    // Generate calendar on page load
    generateCalendar();
</script>
@endsection
