@extends('layouts.layout')

@section('title', 'Dashboard - DailyMood')

@section('content')
<!-- Calendar Section -->
<div class="calendar-container">
    <div class="calendar-header">
        <button class="calendar-nav-btn" onclick="changeMonth(-1)">←</button>
        <div class="calendar-month" id="calendarMonth">
            {{ \Carbon\Carbon::create($currentYear, $currentMonth, 1)->locale('id')->translatedFormat('F Y') }}
        </div>
        <button class="calendar-nav-btn" onclick="changeMonth(1)">→</button>
    </div>
    <div class="calendar-grid" id="calendarGrid">
        <!-- Calendar will be generated by JavaScript -->
    </div>
</div>

<!-- Quick Actions -->
<div class="card" style="text-align: center;">
    <h2 style="margin-bottom: 20px; color: #1a1a2e; font-size: 24px; font-weight: 700;"> Apa Mood Anda Hari Ini?</h2>
    <p style="color: #6c757d; margin-bottom: 25px;">Catat perasaan Anda untuk memahami pola emosi Anda lebih baik.</p>
    <a href="{{ route('daily-moods.create') }}" class="btn btn-primary" style="text-decoration: none; padding: 16px 40px; font-size: 16px;">
        + Tambah Mood Sekarang
    </a>
</div>

<!-- Modal untuk menampilkan riwayat mood -->
<div id="moodHistoryModal" class="mood-modal">
    <div class="mood-modal-content">
        <button onclick="closeMoodHistory()" class="mood-modal-close">&times;</button>
        <h3 id="modalDate" style="margin-bottom: 20px; color: #11a8d2; font-size: 22px; font-weight: 700;"></h3>
        <div id="modalContent"></div>
    </div>
</div>
@endsection

@section('scripts')
<script>
    const moodDates = @json($moodDates);
    const moodsByDate = @json($moodsByDate);
    let currentMonth = {{ $currentMonth }};
    let currentYear = {{ $currentYear }};

    function generateCalendar() {
        const firstDay = new Date(currentYear, currentMonth - 1, 1);
        const lastDay = new Date(currentYear, currentMonth, 0);
        const daysInMonth = lastDay.getDate();
        const startingDayOfWeek = firstDay.getDay();
        
        const dayNames = ['Min', 'Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab'];
        const monthNames = [
            'Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni',
            'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember'
        ];

        document.getElementById('calendarMonth').textContent = 
            monthNames[currentMonth - 1] + ' ' + currentYear;

        let calendarHTML = '';
        
        // Day headers
        dayNames.forEach(day => {
            calendarHTML += `<div class="calendar-day-header">${day}</div>`;
        });

        // Empty cells for days before month starts
        for (let i = 0; i < startingDayOfWeek; i++) {
            calendarHTML += `<div class="calendar-day other-month"></div>`;
        }

        // Days of the month
        const today = new Date();
        today.setHours(0, 0, 0, 0);
        
        for (let day = 1; day <= daysInMonth; day++) {
            const dateStr = `${currentYear}-${String(currentMonth).padStart(2, '0')}-${String(day).padStart(2, '0')}`;
            const dateObj = new Date(currentYear, currentMonth - 1, day);
            dateObj.setHours(0, 0, 0, 0);
            
            const isToday = dateObj.getTime() === today.getTime();
            const hasMood = moodDates.includes(dateStr);
            
            let classes = 'calendar-day';
            if (isToday) classes += ' today';
            if (hasMood) classes += ' has-mood';
            
            // Get mood icon for this date
            let moodIcon = '';
            if (hasMood && moodsByDate[dateStr] && moodsByDate[dateStr].length > 0) {
                const firstMood = moodsByDate[dateStr][0];
                if (firstMood.mood_image) {
                    moodIcon = `<img src="/${firstMood.mood_image}" alt="" class="calendar-mood-icon">`;
                } else if (firstMood.mood_emoji) {
                    moodIcon = `<span class="calendar-mood-emoji">${firstMood.mood_emoji}</span>`;
                }
            }
            
            if (hasMood) {
                calendarHTML += `<div class="${classes}" onclick="showMoodHistory('${dateStr}')" style="cursor: pointer;" title="Klik untuk melihat mood"><span class="calendar-day-num">${day}</span>${moodIcon}</div>`;
            } else if (isToday) {
                calendarHTML += `<div class="${classes}" onclick="window.location.href='{{ route('daily-moods.create') }}'" style="cursor: pointer;" title="Tambah mood hari ini">${day}</div>`;
            } else {
                calendarHTML += `<div class="${classes}">${day}</div>`;
            }
        }

        document.getElementById('calendarGrid').innerHTML = calendarHTML;
    }

    function showMoodHistory(dateStr) {
        const moods = moodsByDate[dateStr];
        if (!moods || moods.length === 0) {
            return;
        }

        const date = new Date(dateStr);
        const options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };
        document.getElementById('modalDate').textContent = '📅 ' + date.toLocaleDateString('id-ID', options);

        let contentHTML = '';
        moods.forEach(mood => {
            const moodImage = mood.mood_image ? `<img src="/${mood.mood_image}" alt="${mood.mood_name}" style="width: 60px; height: 60px; object-fit: contain; border-radius: 12px; box-shadow: 0 2px 8px rgba(0,0,0,0.1);">` : `<span style="font-size: 40px;">${mood.mood_emoji}</span>`;
            
            contentHTML += `
                <div style="background: #f8f9fa; border-left: 4px solid #11a8d2; padding: 20px; border-radius: 16px; margin-bottom: 15px;">
                    <div style="display: flex; align-items: center; gap: 15px; margin-bottom: 12px;">
                        ${moodImage}
                        <div>
                            <h4 style="margin: 0; color: #1a1a2e; font-size: 18px; font-weight: 700;">${mood.mood_name}</h4>
                            <p style="margin: 5px 0 0 0; color: #666; font-size: 14px;">📅 ${mood.mood_date}</p>
                        </div>
                    </div>
                    <p style="margin: 12px 0 0 0; color: #495057; line-height: 1.7; font-size: 14px;"><strong style="color: #11a8d2;">Alasan:</strong> ${mood.reason}</p>
                    <div style="margin-top: 15px;">
                        <a href="/daily-moods/${mood.id}" class="btn btn-primary" style="text-decoration: none; padding: 10px 20px; font-size: 14px; display: inline-block;">👁️ Lihat Detail</a>
                    </div>
                </div>
            `;
        });

        document.getElementById('modalContent').innerHTML = contentHTML;
        document.getElementById('moodHistoryModal').style.display = 'flex';
    }

    function closeMoodHistory() {
        document.getElementById('moodHistoryModal').style.display = 'none';
    }

    function changeMonth(delta) {
        currentMonth += delta;
        if (currentMonth > 12) {
            currentMonth = 1;
            currentYear++;
        } else if (currentMonth < 1) {
            currentMonth = 12;
            currentYear--;
        }
        generateCalendar();
    }

    // Close modal when clicking outside
    document.getElementById('moodHistoryModal').addEventListener('click', function(e) {
        if (e.target === this) {
            closeMoodHistory();
        }
    });

    // Generate calendar on page load
    generateCalendar();
</script>
@endsection
